coverage:
  status:
    project:
      default:
        informational: true
    patch:
      default:
        informational: true
ignore:
  - "conn/stub.go"
  - "mocks"
flag_management:
  default_rules:
    carryforward: true
