before:
  hooks:
    - go mod tidy
builds:
  - env:
      - CGO_ENABLED=0
    goos:
      - darwin
      - linux
      - windows
archives:
  - name_template: "{{ .Os }}-{{ .Arch }}"
    format: binary
snapshot:
  name_template: "{{ .Tag }}-next"
changelog:
  skip: true
release:
  draft: true
