before:
  hooks:
    - go mod tidy
builds:
  - env:
      - CGO_ENABLED=0
    goos:
      - darwin
      - freebsd
      - linux
      - windows
    ldflags:
      - "-X github.com/seachicken/gh-poi/main.Version={{ .Version }}"
archives:
  - name_template: "{{ .Os }}-{{ .Arch }}"
    format: binary
snapshot:
  name_template: "{{ .Tag }}-next"
changelog:
  use: github-native
release:
  draft: true
